version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=quizdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d quizdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/quizdb
      - DB_USERNAME=dbuser
      - DB_PASSWORD=dbpass
      - API_SECRET=dev-secret-123
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=false
      - DATA_PATH=/app/data/
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - spring-backend
    restart: unless-stopped

volumes:
  postgres_data: